# Generated by Django 4.1.1 on 2024-04-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0006_alter_visita_integrantes_familia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='vivienda',
        ),
        migrations.AddField(
            model_name='visita',
            name='vivienda',
            field=models.ManyToManyField(blank=True, null=True, to='visitas.vivienda'),
        ),
    ]
