# Generated by Django 4.1.1 on 2024-03-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='avatar',
            new_name='foto',
        ),
    ]
