# Generated by Django 4.1.1 on 2024-03-05 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('parentezco', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PosiblesRiesgos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violencia_intrafamiliar', models.BooleanField(default=False)),
                ('adicciones', models.BooleanField(default=False)),
                ('otros', models.BooleanField(default=False)),
                ('comentario_otros', models.TextField(blank=True)),
                ('narcotrafico', models.BooleanField(default=False)),
                ('contaminacion', models.BooleanField(default=False)),
                ('vandalismo', models.BooleanField(default=False)),
                ('deslizamiento_tierra', models.BooleanField(default=False)),
                ('delincuencia_visible', models.BooleanField(default=False)),
                ('proximo_canada_rio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('año', models.PositiveIntegerField()),
                ('modo_adquisicion', models.CharField(max_length=100)),
                ('tiempo_con_vehiculo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vivienda', models.CharField(choices=[('Propia', 'Propia'), ('Alquilada', 'Alquilada')], max_length=20)),
                ('tipo_techo', models.CharField(choices=[('Techo Zinc', 'Techo Zinc'), ('Techo Concreto', 'Techo Concreto')], max_length=20)),
                ('tipo_pared', models.CharField(choices=[('Pared Madera', 'Pared Madera'), ('Pared Blocks', 'Pared Blocks')], max_length=20)),
                ('direccion', models.TextField()),
                ('monto_alquiler', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tiempo_ocupando', models.CharField(blank=True, max_length=100, null=True)),
                ('comentario_general', models.TextField(blank=True)),
                ('nevera', models.BooleanField(default=False)),
                ('cantidad_televisores', models.PositiveIntegerField(default=0)),
                ('comentarios_televisores', models.TextField(blank=True)),
                ('lavadora', models.BooleanField(default=False)),
                ('cantidad_aire_acondicionados', models.PositiveIntegerField(default=0)),
                ('comentarios_aire_acondicionados', models.TextField(blank=True)),
                ('secadora', models.BooleanField(default=False)),
                ('computadora', models.BooleanField(default=False)),
                ('cantidad_computadoras', models.PositiveIntegerField(default=0)),
                ('comentario_electrodomesticos', models.TextField(blank=True)),
                ('agua_regular', models.BooleanField(default=False)),
                ('telecable', models.BooleanField(default=False)),
                ('telefono', models.BooleanField(default=False)),
                ('comentario_telefono', models.TextField(blank=True)),
                ('luz_contratada', models.BooleanField(default=False)),
                ('parabola', models.BooleanField(default=False)),
                ('otros_servicios', models.BooleanField(default=False)),
                ('comentario_otros_servicios', models.TextField(blank=True)),
                ('gas', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField()),
                ('tipo_visita', models.CharField(choices=[('Pre-empleo', 'Pre-empleo'), ('Mantenimiento', 'Mantenimiento'), ('Aleatoria', 'Aleatoria')], max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('telefonos', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('ciudad_nacimiento', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('direccion_residencia', models.TextField()),
                ('punto_referencia', models.TextField()),
                ('estado_civil', models.CharField(max_length=20)),
                ('cantidad_dependientes_directos', models.IntegerField()),
                ('monto_alquiler', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tiempo_ocupando', models.CharField(blank=True, max_length=100, null=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_inspeccionadas', to=settings.AUTH_USER_MODEL)),
                ('integrantes_familia', models.ManyToManyField(to='visitas.miembrofamilia')),
                ('responsable_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('vehiculos', models.ManyToManyField(to='visitas.vehiculo')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitas.vivienda')),
            ],
        ),
    ]
