# Generated by Django 4.1.1 on 2024-03-05 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_agendada', models.DateTimeField()),
                ('direccion', models.CharField(max_length=200)),
                ('motivo', models.TextField()),
                ('Observaciones', models.TextField()),
                ('usuario_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_solicitud', to=settings.AUTH_USER_MODEL)),
                ('visitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
