# Generated by Django 4.1.1 on 2024-04-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0003_alter_cita_visitador'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='lat',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visita',
            name='lon',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
