# Generated by Django 4.1.1 on 2024-04-30 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0005_alter_visita_apellidos_alter_visita_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='integrantes_familia',
            field=models.ManyToManyField(blank=True, null=True, to='visitas.miembrofamilia'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='vehiculos',
            field=models.ManyToManyField(blank=True, null=True, to='visitas.vehiculo'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='vivienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitas.vivienda'),
        ),
    ]
