# Generated by Django 4.1.1 on 2024-05-04 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0007_remove_visita_vivienda_visita_vivienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='cita',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='cita_visita', to='visitas.cita'),
            preserve_default=False,
        ),
    ]
