# Generated by Django 4.1.1 on 2024-05-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0008_visita_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estatus',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
