# Generated by Django 4.1.1 on 2024-06-02 02:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitas', '0010_remove_visita_apellidos_remove_visita_cedula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='año',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='modo_adquisicion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tiempo_con_vehiculo',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='ciudad_nacimiento',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='direccion_residencia',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='punto_referencia',
        ),
        migrations.AddField(
            model_name='cita',
            name='ciudad_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='direccion_residencia',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='estado_civil',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2024, 6, 2, 2, 41, 59, 473843)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='puesto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='punto_referencia',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='solcitante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
