# Generated by Django 4.1.1 on 2024-06-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0011_remove_servicio_año_remove_servicio_modo_adquisicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='marca',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
