# Generated by Django 4.1.1 on 2024-06-02 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0012_servicio_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='marca',
        ),
    ]
