# Generated by Django 4.1.1 on 2024-06-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0013_remove_servicio_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='marca',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
