# Generated by Django 4.1.1 on 2024-06-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0014_servicio_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
