# Generated by Django 4.1.1 on 2024-06-02 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0015_alter_servicio_marca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='marca',
            new_name='estatus',
        ),
    ]
