# Generated by Django 4.1.1 on 2024-06-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0016_rename_marca_servicio_estatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_visita',
            field=models.DateTimeField(blank=True),
        ),
    ]
