# Generated by Django 4.1.1 on 2024-06-10 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0018_servicio_visitador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='cantidad_dependientes_directos',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='monto_alquiler',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='tiempo_ocupando',
        ),
    ]
