# Generated by Django 4.1.1 on 2024-06-11 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0019_remove_visita_cantidad_dependientes_directos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 11, 0, 7, 35, 386344)),
            preserve_default=False,
        ),
    ]
