# Generated by Django 4.1.1 on 2024-06-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0020_visita_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='cantidad_computadoras',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
