name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Despliega cuando haya cambios en la rama 'main'
  pull_request:
    branches:
      - main  # Verifica en Pull Requests hacia 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Configurar repositorio
    - name: Checkout Code
      uses: actions/checkout@v3

    # Configurar Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.2"

    # Instalar dependencias
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Testear la aplicación (Esto para cuando se añadan tests)
    - name: Run Tests
      run: |
        python manage.py test

    # Desplegar en Vercel
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-args: "--prod"
        working-directory: .
